# Generated by Django 5.1.7 on 2025-05-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
                ('image_url', models.URLField()),
                ('details', models.TextField()),
                ('control', models.TextField()),
                ('impact', models.TextField()),
                ('severity', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
                ('image_url', models.URLField()),
                ('details', models.TextField()),
                ('control', models.TextField()),
                ('impact', models.TextField()),
                ('infestation_rate', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
